version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: sudo apt-get install -y libpng-dev
      - run: npm install
      - run: npm run test
      - run: ./gradlew test
