version: '2'
services:
    abstrakt-app:
        image: abstrakt
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://abstrakt-postgresql:5432/abstrakt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    abstrakt-postgresql:
        extends:
            file: postgresql.yml
            service: abstrakt-postgresql
